OnlineShop/Areas/Customer/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OnlineShop.Data;
using OnlineShop.Models;
using OnlineShop.Utility;
using X.PagedList;

namespace OnlineShop.Controllers
{
    [Area("Customer")]
    
    public class HomeController : Controller
    {
        private ApplicationDbContext _db;

        public HomeController(ApplicationDbContext db)
        {
            _db = db;
        }

       
        public IActionResult Index(int? page)
        {
            return View(_db.Products.Include(c=>c.ProductTypes).Include(c=>c.SpecialTag).ToList().ToPagedList(page??1,9));
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        
        //GET product detail acation method

        public ActionResult Detail(int? id)
        {
            
            if(id==null)
            {
                return NotFound();
            }

            var product = _db.Products.Include(c => c.ProductTypes).FirstOrDefault(c => c.Id == id);
            if(product==null)
            {
                return NotFound();
            }
            return View(product);
        }

        //POST product detail acation method
        [HttpPost]
        [ActionName("Detail")]
        public ActionResult ProductDetail(int? id)
        {
            List<Products>products=new List<Products>();
            if (id == null)
            {
                return NotFound();
            }

            var product = _db.Products.Include(c => c.ProductTypes).FirstOrDefault(c => c.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            products = HttpContext.Session.Get<List<Products>>("products");
            if(products==null)
            {
                products=new List<Products>();
            }
            products.Add(product);
            HttpContext.Session.Set("products", products);
            return RedirectToAction(nameof(Index));
        }
        //GET Remove action methdo
        [ActionName("Remove")]
        public IActionResult RemoveToCart(int? id)
        {
            List<Products> products = HttpContext.Session.Get<List<Products>>("products");
            if (products != null)
            {
                var product = products.FirstOrDefault(c => c.Id == id);
                if (product != null)
                {
                    products.Remove(product);
                    HttpContext.Session.Set("products", products);
                }
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]

        public IActionResult Remove(int? id)
        {
            List<Products> products = HttpContext.Session.Get<List<Products>>("products");
            if(products!=null)
            {
                var product = products.FirstOrDefault(c => c.Id == id);
                if(product!=null)
                {
                    products.Remove(product);
                    HttpContext.Session.Set("products", products);
                }
            }
            return RedirectToAction(nameof(Index));
        }

        //GET product Cart action method

        public IActionResult Cart()
        {
            List<Products> products = HttpContext.Session.Get<List<Products>>("products");
            if(products==null)
            {
                products=new List<Products>();
            }
            return View(products);
        }

    }
}

OnlineShop/Areas/Customer/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Data;
using OnlineShop.Models;
using OnlineShop.Utility;

namespace OnlineShop.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class OrderController : Controller
    {
        private ApplicationDbContext _db;

        public OrderController(ApplicationDbContext db)
        {
            _db = db;
        }
      
        //GET Checkout actioin method

        public IActionResult Checkout()
        {
            return View();
        }
      
        //POST Checkout action method

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Checkout(Order anOrder)
        {
            List<Products> products = HttpContext.Session.Get<List<Products>>("products");
            if(products!=null)
            {
                foreach (var product in products)
                {
                    OrderDetails orderDetails=new OrderDetails();
                    orderDetails.PorductId = product.Id;
                    anOrder.OrderDetails.Add(orderDetails);
                }
            }

            anOrder.OrderNo = GetOrderNo();
            _db.Orders.Add(anOrder);
            await _db.SaveChangesAsync();
            HttpContext.Session.Set("products", new List<Products>());
            return View();
        }


        public string GetOrderNo()
        {
            int rowCount = _db.Orders.ToList().Count()+1;
            return rowCount.ToString("000");
        }
    }
}

OnlineShop/Areas/Customer/Views/Home/Cart.cshtml
@using OnlineShop.Models
@model List<Products>
@{
    ViewData["Title"] = "Cart";
}

<h1>Your Cart</h1>

<br/>
<div class="row">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Image</th>
            <th>Name</th>
            <th>Price</th>
            <th>Product Type</th>
            <th>Color</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <img src="~/@item.Image" width="200px" height="150px"/>
                </td>
                <td>@item.Name</td>
                <td>@item.Price</td>
                <td>@item.ProductTypes.ProductType</td>
                <td>@item.ProductColor</td>
                <td>
                    <a asp-area="Customer" asp-action="Remove" asp-controller="Home" asp-route-id="@item.Id" class="btn btn-danger">
                        <i class="fas fa-trash-alt"></i>
                    </a>
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>
<div class="row">
    <div class="col-6">
        <a asp-action="Index" asp-controller="Home" class="btn btn-success">Back to Home</a>
    </div>
    <div class="col-6 text-right">
        <h3>Total Amount</h3>
        <h3>Grant Total : @Model.Sum(c=>c.Price) </h3>
        <a asp-area="Customer" asp-action="Checkout" asp-controller="Order" class="btn btn-info">Process to Checkout</a>
    </div>
</div>

OnlineShop/Areas/Customer/Views/Home/Detail.cshtml
@model OnlineShop.Models.Products
@{
    ViewData["Title"] = "Details";

}
@using OnlineShop.Utility
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@{

    List<Products> products = HttpContextAccessor.HttpContext.Session.Get<List<Products>>("products");
    Products product = null;
    if (products != null)
    {
        product = products.FirstOrDefault(c => c.Id == Model.Id);
    }

}
<br />

<h2 class="text-info">Product Details</h2>
<form asp-action="Detail" method="post" enctype="multipart/form-data">
    <div class="p-4 rounded border row">
        <div asp-validation-summary="ModelOnly" class="text-danger">

        </div>
        <div class="col-8">
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Name"></label>
                </div>
                <div class="col-8">
                    <input type="hidden" asp-for="Id" />
                    <input asp-for="Name" readonly="readonly" class="form-control" />
                </div>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Price"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Price" readonly="readonly" class="form-control" />
                </div>
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            @*<div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Image"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Image" class="form-control" type="file" />
                    </div>
                    <span asp-validation-for="Image" class="text-danger"></span>
                </div>*@
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="ProductColor"></label>
                </div>
                <div class="col-8">
                    <input asp-for="ProductColor" readonly="readonly" readonly="readonly" class="form-control" />
                </div>
                <span asp-validation-for="ProductColor" class="text-danger"></span>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="ProductTypeId"></label>
                </div>
                <div class="col-8">
                    @*<select asp-for="ProductTypeId" asp-items="ViewBag.productTypeId" class="form-control"></select>*@
                    <input asp-for="ProductTypes.ProductType" readonly="readonly" class="form-control" />
                </div>
                <span asp-validation-for="ProductTypeId" class="text-danger"></span>
            </div>

            <div class="form-group row">
                <div class="col-4">

                </div>
                <div class="col-8">
                    @if (product != null)
                    {
                        <button type="submit" class="btn btn-danger form-control" asp-action="Remove" asp-route-id="@Model.Id">Remove to Cart</button>
                    }
                    else
                    {
                        <input type="submit" class="btn btn-info form-control" value="Add to Cart" />
                    }
                    
                </div>

            </div>
            <div class="form-group">
                <a asp-action="Index" class="btn btn-success">Back to List</a>
            </div>
        </div>
        <div class="col-1"></div>
        <div class="col-3">
            <img src="~/@Model.Image" width="100%" height="250px" style="border-radius: 5px;border: 1px solid #efefef" />
            @if (Model.IsAvailable)
            {
                <img src="~/Images/instock-logo.png" width="200px" height="50px" />
            }
            else
            {
                <img src="~/Images/notinstock.jpg" width="200px" height="50px" />
            }

        </div>

    </div>
</form>

@section Scripts{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

OnlineShop/Areas/Customer/Views/Home/Index.cshtml
@using OnlineShop.Models;
@using X.PagedList.Mvc.Common
@using X.PagedList.Mvc.Core
@model X.PagedList.IPagedList<Products>
@{
    ViewData["Title"] = "Home Page";
}
<br/><br/>
<div class="row">
    @foreach (var product in Model)
    {
        <div class="col-4">
            <div class="card mb-4">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">
                        <label style="font-size: 23px;color: steelblue">@product.Name</label>
                    </h4>
                </div>
                <img src="~/@product.Image" alt="Card Image" class="card-img-top" style="height: 300px;"/>
                <div class="card-header">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <label style="font-size: 20px;color: #a51313"><b>Price : @product.Price</b></label>
                        </div>
                        <a asp-action="Detail" asp-controller="Home" asp-route-id="@product.Id" class="btn btn-success pull-right btn-outline-info">Deatils</a>
                    </div>
                </div>
            </div>
        </div>
    }
</div>
<div>
    @Html.PagedListPager(Model,c=>Href("~/Customer/Home/Index?page="+c),PagedListRenderOptionsBase.PageNumbersOnly)
</div>